Repository SwEnt-Group8/Street-work-app, pull requests merged in 2024-10, with the labels that each got.

#19 Doc/GitHub badges
  README.md
Labels: documentation

#11 Feature/7 add localisation managment
  app/build.gradle.kts
  app/src/androidTest/java/com/android/streetworkapp/ui/map/MapTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/android/streetworkapp/ui/map/Map.kt
  app/src/main/java/com/android/streetworkapp/ui/theme/Color.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/com/android/streetworkapp/ExampleRobolectricTest.kt
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: Enhancement :sparkles:

#20 Feature/9 park details events UI
  app/build.gradle.kts
  app/src/androidTest/java/com/android/streetworkapp/ui/parkoverview/ParkOverviewTest.kt
  app/src/main/java/com/android/streetworkapp/model/event/Event.kt
  app/src/main/java/com/android/streetworkapp/model/park/Park.kt
  app/src/main/java/com/android/streetworkapp/model/parklocation/OverpassParkLocationRepository.kt
  app/src/main/java/com/android/streetworkapp/model/parklocation/ParkLocation.kt
  app/src/main/java/com/android/streetworkapp/model/parklocation/ParkLocationRepository.kt
  app/src/main/java/com/android/streetworkapp/model/parklocation/ParkLocationViewModel.kt
  app/src/main/java/com/android/streetworkapp/ui/park/ParkOverview.kt
  app/src/main/java/com/android/streetworkapp/utils/DateUtils.kt
  app/src/main/res/drawable/park_default.png
  app/src/test/java/com/android/streetworkapp/model/parklocation/OverpassParkLocationRepositoryTest.kt
  app/src/test/java/com/android/streetworkapp/model/parklocation/ParkLocationViewModelTest.kt
  gradle/libs.versions.toml
Labels: Enhancement :sparkles:

#25 Update the readme
  README.md
Labels: Documentation :page_facing_up:

#22 Feature/14 implement map UI
  .github/workflows/ci.yml
  .gitignore
  app/build.gradle.kts
  app/src/androidTest/java/com/android/streetworkapp/ui/MainActivityTest.kt
  app/src/androidTest/java/com/android/streetworkapp/ui/map/MapUiTest.kt
  app/src/androidTest/java/com/android/streetworkapp/ui/navigation/BottomNavigationTest.kt
  app/src/androidTest/java/com/android/streetworkapp/ui/navigation/NavigationActionsTestUi.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/android/streetworkapp/ui/map/MapUi.kt
  app/src/main/java/com/android/streetworkapp/ui/navigation/BottomNavigationMenu.kt
  build.gradle.kts
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.properties
Labels: Enhancement :sparkles:

#21 Feature/18 implement profile UI
  app/build.gradle.kts
  app/src/androidTest/java/com/android/streetworkapp/ui/profile/ProfileScreenTest.kt
  app/src/main/java/com/android/streetworkapp/MainActivity.kt
  app/src/main/java/com/android/streetworkapp/ui/profile/Profile.kt
  app/src/main/res/drawable/profile.png
  app/src/main/res/drawable/qrcode.png
Labels: Enhancement :sparkles:

#27 Feat/GitHub release integration
  .github/workflows/apk-builder.yml
Labels: Enhancement :sparkles:

#37 Feat/UI to create new events
  app/build.gradle.kts
  app/src/androidTest/java/com/android/streetworkapp/ui/parkoverview/AddEventTest.kt
  app/src/main/java/com/android/streetworkapp/model/event/Event.kt
  app/src/main/java/com/android/streetworkapp/ui/park/AddEvent.kt
  gradle/libs.versions.toml
Labels: Enhancement :sparkles:

#23 Feature/12 implement sign up and log into the app
  .github/workflows/ci.yml
  app/build.gradle.kts
  app/src/androidTest/java/com/android/streetworkapp/end2end/End2EndParks.kt
  app/src/androidTest/java/com/android/streetworkapp/ui/authentication/SignInTest.kt
  app/src/main/java/com/android/streetworkapp/MainActivity.kt
  app/src/main/java/com/android/streetworkapp/ui/authentication/GoogleAuthButton.kt
  app/src/main/java/com/android/streetworkapp/ui/authentication/SignIn.kt
  app/src/main/java/com/android/streetworkapp/ui/theme/Color.kt
  app/src/main/java/com/android/streetworkapp/ui/theme/Type.kt
  app/src/main/java/com/android/streetworkapp/utils/AuthService.kt
  app/src/main/java/com/android/streetworkapp/utils/GoogleAuthService.kt
  app/src/main/res/drawable/google_logo.png
  app/src/main/res/values/strings.xml
  build.gradle.kts
  gradle/libs.versions.toml
Labels: Enhancement :sparkles:

#35 Feat/event overview UI
  app/build.gradle.kts
  app/src/androidTest/java/com/android/streetworkapp/ui/map/MapUiTest.kt
  app/src/androidTest/java/com/android/streetworkapp/ui/navigation/BottomNavigationTest.kt
  app/src/androidTest/java/com/android/streetworkapp/ui/navigation/BottomNavigationTest.kt~
  app/src/androidTest/java/com/android/streetworkapp/ui/parkoverview/EventOverviewTest.kt
  app/src/androidTest/java/com/android/streetworkapp/ui/parkoverview/ParkOverviewTest.kt
  app/src/main/java/com/android/streetworkapp/MainActivity.kt
  app/src/main/java/com/android/streetworkapp/model/park/Park.kt
  app/src/main/java/com/android/streetworkapp/ui/park/EventOverview.kt
  app/src/main/java/com/android/streetworkapp/ui/theme/Color.kt
  gradle/libs.versions.toml
Labels: Enhancement :sparkles:

#41 Implement the parks MVVM
  app/src/androidTest/java/com/android/streetworkapp/ui/parkoverview/EventOverviewTest.kt
  app/src/androidTest/java/com/android/streetworkapp/ui/parkoverview/ParkOverviewTest.kt
  app/src/main/java/com/android/streetworkapp/MainActivity.kt
  app/src/main/java/com/android/streetworkapp/model/park/Park.kt
  app/src/main/java/com/android/streetworkapp/model/park/ParkRepository.kt
  app/src/main/java/com/android/streetworkapp/model/park/ParkRepositoryFirestore.kt
  app/src/main/java/com/android/streetworkapp/model/park/ParkViewModel.kt
  app/src/main/java/com/android/streetworkapp/ui/park/EventOverview.kt
  app/src/main/java/com/android/streetworkapp/ui/park/ParkOverview.kt
  app/src/test/java/com/android/streetworkapp/model/park/ParkRepositoryFirestoreTest.kt
  app/src/test/java/com/android/streetworkapp/model/park/ParkTest.kt
  app/src/test/java/com/android/streetworkapp/model/park/ParkViewModelTest.kt
Labels: Enhancement :sparkles:

#46 Make the AddEvent Screen functional
  app/src/androidTest/java/com/android/streetworkapp/end2end/End2EndParks.kt
  app/src/androidTest/java/com/android/streetworkapp/ui/parkoverview/AddEventTest.kt
  app/src/main/java/com/android/streetworkapp/MainActivity.kt
  app/src/main/java/com/android/streetworkapp/model/event/Event.kt
  app/src/main/java/com/android/streetworkapp/model/event/EventRepository.kt
  app/src/main/java/com/android/streetworkapp/model/event/EventRepositoryFirestore.kt
  app/src/main/java/com/android/streetworkapp/model/event/EventViewModel.kt
  app/src/main/java/com/android/streetworkapp/ui/navigation/NavigationActions.kt
  app/src/main/java/com/android/streetworkapp/ui/park/AddEvent.kt
  app/src/main/java/com/android/streetworkapp/ui/park/ParkOverview.kt
  app/src/test/java/com/android/streetworkapp/model/event/EventRepositoryFirestoreTest.kt
  app/src/test/java/com/android/streetworkapp/model/event/EventViewModelTest.kt
Labels: Enhancement :sparkles:

#51 Hotfix Park MVVM
  app/src/main/java/com/android/streetworkapp/model/park/ParkViewModel.kt
  app/src/test/java/com/android/streetworkapp/model/park/ParkViewModelTest.kt
Labels: Enhancement :sparkles:, Fixed bug ✅
