Repository SwEnt-Group8/Street-work-app, pull requests merged in 2024-12, with the labels that each got.

#180 Linking infodialogs with strings.xml file to avoid hard-coded strings
  app/src/androidTest/java/com/android/streetworkapp/ui/navigation/InfoDialogsTest.kt
  app/src/main/java/com/android/streetworkapp/MainActivity.kt
  app/src/main/java/com/android/streetworkapp/ui/navigation/InfoDialogs.kt
Labels: Refactor 🛠️

#178 Feat/Preferences MVVM
  app/build.gradle.kts
  app/src/main/java/com/android/streetworkapp/model/preferences/PreferencesRepository.kt
  app/src/main/java/com/android/streetworkapp/model/preferences/PreferencesRepositoryDataStore.kt
  app/src/main/java/com/android/streetworkapp/model/preferences/PreferencesViewModel.kt
  app/src/test/java/com/android/streetworkapp/model/preferences/PreferencesViewModelTest.kt
  gradle/libs.versions.toml
Labels: Enhancement :sparkles:

#168 fix: adapt failling dates tests
  app/src/test/java/com/android/streetworkapp/model/workout/WorkoutSessionTest.kt
  app/src/test/java/com/android/streetworkapp/utils/DateUtilsTest.kt
Labels: Bug :bug:

#179 Make composable to take pictures of parks
  app/src/androidTest/java/com/android/streetworkapp/ui/image/ConfirmImageDialogTest.kt
  app/src/androidTest/java/com/android/streetworkapp/ui/parkoverview/ParkOverviewTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/android/streetworkapp/ui/image/AddImageButton.kt
  app/src/main/java/com/android/streetworkapp/ui/image/ConfirmImageDialog.kt
  app/src/main/java/com/android/streetworkapp/ui/park/ParkOverview.kt
  app/src/main/res/drawable/add_a_photo_24px.xml
  app/src/main/res/xml/file_paths.xml
Labels: Enhancement :sparkles:

#186 Feat/Improve progression screen with achievements linked to social interactions
  app/src/androidTest/java/com/android/streetworkapp/ui/Progression/ProgressionTest.kt
  app/src/main/java/com/android/streetworkapp/model/progression/Progression.kt
  app/src/main/java/com/android/streetworkapp/model/progression/ProgressionViewModel.kt
  app/src/main/java/com/android/streetworkapp/ui/progress/Progression.kt
  app/src/main/res/drawable/first_friend_achievement.png
  app/src/main/res/drawable/group_friend_achievement.png
  app/src/main/res/values/strings.xml
Labels: Enhancement :sparkles:

#191 Hotfix/fix UI issues
  app/src/androidTest/java/com/android/streetworkapp/ui/parkoverview/ParkOverviewTest.kt
  app/src/androidTest/java/com/android/streetworkapp/ui/profile/AddFriendScreenTest.kt
  app/src/main/java/com/android/streetworkapp/MainActivity.kt
  app/src/main/java/com/android/streetworkapp/ui/event/AddEvent.kt
  app/src/main/java/com/android/streetworkapp/ui/navigation/TopAppBar.kt
  app/src/main/java/com/android/streetworkapp/ui/park/ParkOverview.kt
  app/src/main/java/com/android/streetworkapp/ui/profile/AddFriend.kt
  app/src/main/java/com/android/streetworkapp/ui/profile/BluetoothButton.kt
  app/src/main/java/com/android/streetworkapp/ui/profile/Profile.kt
  app/src/main/java/com/android/streetworkapp/ui/theme/Color.kt
  app/src/main/res/drawable/calendar_add_on.png
Labels: Fixed bug ✅, Refactor 🛠️

#185 Feat/implement friends deletion through per friend parameter
  app/src/androidTest/java/com/android/streetworkapp/ui/profile/ProfileComponentsTest.kt
  app/src/androidTest/java/com/android/streetworkapp/ui/profile/RemoveFriendTest.kt
  app/src/androidTest/java/com/android/streetworkapp/ui/utils/CustomDialogTest.kt
  app/src/main/java/com/android/streetworkapp/ui/profile/Profile.kt
  app/src/main/java/com/android/streetworkapp/ui/utils/CustomDialog.kt
  app/src/main/res/drawable/person_remove.png
  app/src/main/res/values/strings.xml
Labels: Enhancement :sparkles:

#195 Feat/finish implementing the settings for the profile
  app/src/androidTest/java/com/android/streetworkapp/ui/profile/SettingsTest.kt
  app/src/main/java/com/android/streetworkapp/MainActivity.kt
  app/src/main/java/com/android/streetworkapp/ui/profile/Settings.kt
  app/src/main/res/values/strings.xml
Labels: Enhancement :sparkles:

#193 Feat/Login state caching
  app/src/androidTest/java/com/android/streetworkapp/end2end/End2EndCreateEvent.kt
  app/src/androidTest/java/com/android/streetworkapp/end2end/End2EndGeneral.kt
  app/src/androidTest/java/com/android/streetworkapp/end2end/End2EndParks.kt
  app/src/androidTest/java/com/android/streetworkapp/ui/StreetWorkAppMainTest.kt
  app/src/androidTest/java/com/android/streetworkapp/ui/map/MapUiTest.kt
  app/src/androidTest/java/com/android/streetworkapp/ui/miscellaneous/SplashScreenUiTest.kt
  app/src/androidTest/java/com/android/streetworkapp/ui/navigation/BottomNavigationTest.kt
  app/src/androidTest/java/com/android/streetworkapp/ui/navigation/NavigationActionsTestUi.kt
  app/src/androidTest/java/com/android/streetworkapp/ui/navigation/TopAppBarTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/android/streetworkapp/MainActivity.kt
  app/src/main/java/com/android/streetworkapp/device/network/NetworkUtils.kt
  app/src/main/java/com/android/streetworkapp/model/preferences/PreferencesViewModel.kt
  app/src/main/java/com/android/streetworkapp/ui/authentication/SignIn.kt
  app/src/main/java/com/android/streetworkapp/ui/map/MapUi.kt
  app/src/main/java/com/android/streetworkapp/ui/miscellaneous/SplashScreen.kt
Labels: Enhancement :sparkles:

#192 Feat/Complete the SoloTraining
  app/src/androidTest/java/com/android/streetworkapp/ui/navigation/BottomNavigationTest.kt
  app/src/androidTest/java/com/android/streetworkapp/ui/train/TrainChallengeScreenTest.kt
  app/src/androidTest/java/com/android/streetworkapp/ui/train/TrainCoachScreenTest.kt
  app/src/androidTest/java/com/android/streetworkapp/ui/train/TrainParamScreenTest.kt
  app/src/androidTest/java/com/android/streetworkapp/ui/train/TrainSoloScreenTest.kt
  app/src/main/java/com/android/streetworkapp/MainActivity.kt
  app/src/main/java/com/android/streetworkapp/model/workout/WorkoutRepository.kt
  app/src/main/java/com/android/streetworkapp/model/workout/WorkoutRepositoryFirestore.kt
  app/src/main/java/com/android/streetworkapp/model/workout/WorkoutSession.kt
  app/src/main/java/com/android/streetworkapp/model/workout/WorkoutViewModel.kt
  app/src/main/java/com/android/streetworkapp/ui/navigation/NavigationActions.kt
  app/src/main/java/com/android/streetworkapp/ui/train/CircularTimer.kt
  app/src/main/java/com/android/streetworkapp/ui/train/TrainChallengeScreen.kt
  app/src/main/java/com/android/streetworkapp/ui/train/TrainCoachScreen.kt
  app/src/main/java/com/android/streetworkapp/ui/train/TrainHubScreen.kt
  app/src/main/java/com/android/streetworkapp/ui/train/TrainParamScreen.kt
  app/src/main/java/com/android/streetworkapp/ui/train/TrainSoloScreen.kt
  app/src/main/java/com/android/streetworkapp/ui/utils/NavHelper.kt
  app/src/main/java/com/android/streetworkapp/utils/GraphData.kt
  app/src/main/res/drawable/training.png
  app/src/main/res/values/strings.xml
  app/src/test/java/com/android/streetworkapp/model/workout/WorkoutDataTest.kt
  app/src/test/java/com/android/streetworkapp/model/workout/WorkoutRepositoryFirestoreTest.kt
  app/src/test/java/com/android/streetworkapp/model/workout/WorkoutSessionTest.kt
  app/src/test/java/com/android/streetworkapp/model/workout/WorkoutViewModelTest.kt
  app/src/test/java/com/android/streetworkapp/ui/navigation/NavigationActionsTest.kt
  app/src/test/java/com/android/streetworkapp/ui/train/TrainParamScreenTest.kt
  app/src/test/java/com/android/streetworkapp/ui/train/TrainSoloScreenTest.kt
Labels: Enhancement :sparkles:

#201 Setup image backend & early draft for the park image collection composable
  app/src/androidTest/java/com/android/streetworkapp/end2end/End2EndCreateEvent.kt
  app/src/androidTest/java/com/android/streetworkapp/end2end/End2EndGeneral.kt
  app/src/androidTest/java/com/android/streetworkapp/end2end/End2EndParks.kt
  app/src/androidTest/java/com/android/streetworkapp/ui/image/ConfirmImageDialogTest.kt
  app/src/androidTest/java/com/android/streetworkapp/ui/image/ImagesCollectionPopUpTest.kt
  app/src/androidTest/java/com/android/streetworkapp/ui/navigation/BottomNavigationTest.kt
  app/src/androidTest/java/com/android/streetworkapp/ui/navigation/TopAppBarTest.kt
  app/src/androidTest/java/com/android/streetworkapp/ui/parkoverview/ParkOverviewTest.kt
  app/src/main/java/com/android/streetworkapp/MainActivity.kt
  app/src/main/java/com/android/streetworkapp/model/image/ImageModels.kt
  app/src/main/java/com/android/streetworkapp/model/image/ImageRepository.kt
  app/src/main/java/com/android/streetworkapp/model/image/ImageRepositoryFirestore.kt
  app/src/main/java/com/android/streetworkapp/model/image/ImageViewModel.kt
  app/src/main/java/com/android/streetworkapp/model/park/Park.kt
  app/src/main/java/com/android/streetworkapp/model/park/ParkRepository.kt
  app/src/main/java/com/android/streetworkapp/model/park/ParkRepositoryFirestore.kt
  app/src/main/java/com/android/streetworkapp/ui/image/AddImageButton.kt
  app/src/main/java/com/android/streetworkapp/ui/image/ConfirmImageDialog.kt
  app/src/main/java/com/android/streetworkapp/ui/image/FullScreenImagePopup.kt
  app/src/main/java/com/android/streetworkapp/ui/image/ImagesCollectionButton.kt
  app/src/main/java/com/android/streetworkapp/ui/park/ParkOverview.kt
  app/src/main/res/drawable/photo_library_24px.xml
  app/src/test/java/com/android/streetworkapp/model/image/ImageRepositoryFirestoreTest.kt
  app/src/test/java/com/android/streetworkapp/model/image/ImageViewModelTest.kt
  app/src/test/java/com/android/streetworkapp/model/park/ParkRepositoryFirestoreTest.kt
Labels: Enhancement :sparkles:

#202 Refactor/merge checkFriend and checkScore in Progression MVVM
  app/src/main/java/com/android/streetworkapp/model/progression/Progression.kt
  app/src/main/java/com/android/streetworkapp/model/progression/ProgressionViewModel.kt
  app/src/main/java/com/android/streetworkapp/ui/progress/Gamification.kt
  app/src/main/java/com/android/streetworkapp/ui/progress/Progression.kt
  app/src/test/java/com/android/streetworkapp/model/progression/ProgressionViewModelTest.kt
Labels: Refactor 🛠️

#203 Test/end2end workout solo
  app/src/androidTest/java/com/android/streetworkapp/end2end/End2EndWorkoutTraining.kt
  app/src/androidTest/java/com/android/streetworkapp/ui/authentication/SignInTest.kt
  app/src/main/java/com/android/streetworkapp/MainActivity.kt
  app/src/main/java/com/android/streetworkapp/ui/train/AnimatedCounter.kt
  app/src/main/java/com/android/streetworkapp/ui/train/TrainSoloScreen.kt
  app/src/main/java/com/android/streetworkapp/utils/GraphData.kt
Labels: Enhancement :sparkles:

#206 Feat/ Create achievements for training with the app
  app/src/androidTest/java/com/android/streetworkapp/ui/Progression/ProgressionTest.kt
  app/src/main/java/com/android/streetworkapp/MainActivity.kt
  app/src/main/java/com/android/streetworkapp/ui/progress/Progression.kt
  app/src/main/res/values/strings.xml
Labels: Enhancement :sparkles:

#204 Feat/Logout
  app/src/androidTest/java/com/android/streetworkapp/end2end/End2EndCreateEvent.kt
  app/src/androidTest/java/com/android/streetworkapp/end2end/End2EndGeneral.kt
  app/src/androidTest/java/com/android/streetworkapp/end2end/End2EndParks.kt
  app/src/androidTest/java/com/android/streetworkapp/end2end/End2EndWorkoutTraining.kt
  app/src/androidTest/java/com/android/streetworkapp/ui/navigation/BottomNavigationTest.kt
  app/src/androidTest/java/com/android/streetworkapp/ui/navigation/TopAppBarTest.kt
  app/src/androidTest/java/com/android/streetworkapp/ui/profile/SettingsTest.kt
  app/src/main/java/com/android/streetworkapp/MainActivity.kt
  app/src/main/java/com/android/streetworkapp/model/user/UserViewModel.kt
  app/src/main/java/com/android/streetworkapp/ui/authentication/GoogleAuthButton.kt
  app/src/main/java/com/android/streetworkapp/ui/authentication/SignIn.kt
  app/src/main/java/com/android/streetworkapp/ui/profile/Settings.kt
  app/src/main/java/com/android/streetworkapp/utils/AuthService.kt
  app/src/main/java/com/android/streetworkapp/utils/GoogleAuthService.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/com/android/streetworkapp/model/user/UserViewModelTest.kt
Labels: Enhancement :sparkles:

#219 Setup online file storage system
  app/build.gradle.kts
  app/src/main/java/com/android/streetworkapp/MainActivity.kt
  app/src/main/java/com/android/streetworkapp/model/storage/S3StorageClient.kt
  gradle/libs.versions.toml
Labels: Enhancement :sparkles:

#212 Feat/Workout MVVM update
  app/src/main/java/com/android/streetworkapp/model/workout/PairingRequest.kt
  app/src/main/java/com/android/streetworkapp/model/workout/WorkoutRepository.kt
  app/src/main/java/com/android/streetworkapp/model/workout/WorkoutRepositoryFirestore.kt
  app/src/main/java/com/android/streetworkapp/model/workout/WorkoutSession.kt
  app/src/main/java/com/android/streetworkapp/model/workout/WorkoutViewModel.kt
  app/src/test/java/com/android/streetworkapp/model/workout/WorkoutRepositoryFirestoreTest.kt
  app/src/test/java/com/android/streetworkapp/model/workout/WorkoutViewModelTest.kt
Labels: Enhancement :sparkles:

#210 Feat/event management
  app/src/androidTest/java/com/android/streetworkapp/ui/event/AddEventTest.kt
  app/src/androidTest/java/com/android/streetworkapp/ui/event/EventOverviewTest.kt
  app/src/androidTest/java/com/android/streetworkapp/ui/navigation/BottomNavigationTest.kt
  app/src/androidTest/java/com/android/streetworkapp/ui/navigation/TopAppBarTest.kt
  app/src/androidTest/java/com/android/streetworkapp/ui/parkoverview/ParkOverviewTest.kt
  app/src/main/java/com/android/streetworkapp/MainActivity.kt
  app/src/main/java/com/android/streetworkapp/model/event/Event.kt
  app/src/main/java/com/android/streetworkapp/model/event/EventRepository.kt
  app/src/main/java/com/android/streetworkapp/model/event/EventRepositoryFirestore.kt
  app/src/main/java/com/android/streetworkapp/model/event/EventViewModel.kt
  app/src/main/java/com/android/streetworkapp/ui/event/AddEvent.kt
  app/src/main/java/com/android/streetworkapp/ui/event/EventOverview.kt
  app/src/main/java/com/android/streetworkapp/ui/navigation/BottomNavigationMenu.kt
  app/src/main/java/com/android/streetworkapp/ui/navigation/NavigationActions.kt
  app/src/main/java/com/android/streetworkapp/ui/park/ParkOverview.kt
  app/src/main/java/com/android/streetworkapp/ui/theme/Color.kt
  app/src/main/java/com/android/streetworkapp/utils/DateUtils.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/com/android/streetworkapp/model/event/EventRepositoryFirestoreTest.kt
  app/src/test/java/com/android/streetworkapp/model/event/EventViewModelTest.kt
Labels: Enhancement :sparkles:

#225 fix: fixed erroneous string.xml use in park overview screen
  app/src/androidTest/java/com/android/streetworkapp/ui/parkoverview/ParkOverviewTest.kt
  app/src/main/java/com/android/streetworkapp/ui/park/ParkOverview.kt
  app/src/main/java/com/android/streetworkapp/utils/DateUtils.kt
Labels: Fixed bug ✅

#229 Feat/make icon change color in function of nb event
  app/src/main/java/com/android/streetworkapp/ui/map/MapUi.kt
  app/src/main/java/com/android/streetworkapp/ui/theme/Color.kt
  app/src/test/java/com/android/streetworkapp/ui/map/ColorTest.kt
Labels: Enhancement :sparkles:

#234 Feat/Finalize and improve the aesthetics of the progression UI
  app/src/androidTest/java/com/android/streetworkapp/ui/Progression/ProgressionTest.kt
  app/src/main/java/com/android/streetworkapp/model/progression/Progression.kt
  app/src/main/java/com/android/streetworkapp/ui/progress/Progression.kt
  app/src/main/res/drawable/bronze_icon_final.png
  app/src/main/res/drawable/gold_icon_final.png
  app/src/main/res/drawable/platinum_icon_final.png
  app/src/main/res/drawable/silver_icon_final.png
  app/src/main/res/values/strings.xml
Labels: Enhancement :sparkles:

#216 Fix/e2e create event
  app/src/androidTest/java/com/android/streetworkapp/end2end/End2EndCreateEvent.kt
  app/src/androidTest/java/com/android/streetworkapp/ui/event/EventOverviewTest.kt
  app/src/main/java/com/android/streetworkapp/MainActivity.kt
  app/src/main/java/com/android/streetworkapp/model/park/ParkRepositoryFirestore.kt
  app/src/main/java/com/android/streetworkapp/model/park/ParkViewModel.kt
  app/src/main/java/com/android/streetworkapp/model/preferences/PreferencesViewModel.kt
  app/src/main/java/com/android/streetworkapp/model/workout/WorkoutViewModel.kt
  app/src/main/java/com/android/streetworkapp/ui/map/MapUi.kt
Labels: Refactor 🛠️

#224 Feat/implement UI for event filtering
  app/src/androidTest/java/com/android/streetworkapp/ui/map/ParkFilterTest.kt
  app/src/main/java/com/android/streetworkapp/MainActivity.kt
  app/src/main/java/com/android/streetworkapp/model/event/EventViewModel.kt
  app/src/main/java/com/android/streetworkapp/ui/map/MapUi.kt
  app/src/main/java/com/android/streetworkapp/ui/navigation/NavigationActions.kt
  app/src/main/java/com/android/streetworkapp/ui/navigation/TopAppBarManager.kt
  app/src/main/java/com/android/streetworkapp/ui/park/ParkOverview.kt
  app/src/main/java/com/android/streetworkapp/utils/ParkFilter.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/com/android/streetworkapp/utils/ParkFilterTest.kt
Labels: Enhancement :sparkles:

#232 Feat/training coach debug
  app/src/androidTest/java/com/android/streetworkapp/ui/train/TrainCoachScreenTest.kt
  app/src/androidTest/java/com/android/streetworkapp/ui/train/TrainHubScreenTest.kt
  app/src/test/java/com/android/streetworkapp/model/workout/WorkoutViewModelTest.kt
Labels: Bug :bug:, Fixed bug ✅

#239 Refactor/map UI
  app/src/androidTest/java/com/android/streetworkapp/ui/map/MapUiTest.kt
  app/src/androidTest/java/com/android/streetworkapp/ui/navigation/TopAppBarActionTest.kt
  app/src/main/java/com/android/streetworkapp/MainActivity.kt
  app/src/main/java/com/android/streetworkapp/ui/map/MapUi.kt
  app/src/main/java/com/android/streetworkapp/ui/navigation/NavigationActions.kt
  app/src/main/java/com/android/streetworkapp/ui/navigation/TopAppBar.kt
  app/src/main/java/com/android/streetworkapp/ui/navigation/TopAppBarManager.kt
  app/src/main/res/values/strings.xml
Labels: Enhancement :sparkles:, Refactor 🛠️

#245 Feat/update the helping dialogs
  app/src/main/java/com/android/streetworkapp/MainActivity.kt
  app/src/main/java/com/android/streetworkapp/ui/navigation/InfoDialogs.kt
  app/src/main/java/com/android/streetworkapp/ui/navigation/NavigationActions.kt
  app/src/main/res/values/strings.xml
Labels: Enhancement :sparkles:

#249 Hotfix/Navigate to tutorial after sign in
  app/src/main/java/com/android/streetworkapp/ui/authentication/SignIn.kt
Labels: Fixed bug ✅

#231 Feat/training coach frontend final
  app/src/androidTest/java/com/android/streetworkapp/end2end/End2EndGeneral.kt
  app/src/androidTest/java/com/android/streetworkapp/ui/train/TrainCoachScreenTest.kt
  app/src/androidTest/java/com/android/streetworkapp/ui/train/TrainHelperTest.kt
  app/src/androidTest/java/com/android/streetworkapp/ui/train/TrainHubScreenTest.kt
  app/src/main/java/com/android/streetworkapp/MainActivity.kt
  app/src/main/java/com/android/streetworkapp/model/workout/Exercise.kt
  app/src/main/java/com/android/streetworkapp/model/workout/PairingRequest.kt
  app/src/main/java/com/android/streetworkapp/model/workout/WorkoutRepository.kt
  app/src/main/java/com/android/streetworkapp/model/workout/WorkoutRepositoryFirestore.kt
  app/src/main/java/com/android/streetworkapp/model/workout/WorkoutSession.kt
  app/src/main/java/com/android/streetworkapp/model/workout/WorkoutViewModel.kt
  app/src/main/java/com/android/streetworkapp/ui/navigation/NavigationActions.kt
  app/src/main/java/com/android/streetworkapp/ui/progress/Progression.kt
  app/src/main/java/com/android/streetworkapp/ui/train/TrainCoachScreen.kt
  app/src/main/java/com/android/streetworkapp/ui/train/TrainHelper.kt
  app/src/main/java/com/android/streetworkapp/ui/train/TrainHubScreen.kt
  app/src/main/java/com/android/streetworkapp/ui/train/TrainParamScreen.kt
  app/src/main/java/com/android/streetworkapp/ui/train/TrainSoloScreen.kt
  app/src/main/java/com/android/streetworkapp/utils/IconsUtils.kt
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  app/src/test/java/com/android/streetworkapp/model/workout/WorkoutRepositoryFirestoreTest.kt
  app/src/test/java/com/android/streetworkapp/model/workout/WorkoutViewModelTest.kt
Labels: Enhancement :sparkles:

#246 docs/update the readme
  README.md
Labels: Documentation :page_facing_up:
