Repository SwEnt-Group8/Street-work-app, pull requests merged in 2024-11, with the labels that each got.

#59 Hotfix: Update the add event screen to have a park id in each event.
  app/src/androidTest/java/com/android/streetworkapp/ui/parkoverview/AddEventTest.kt
  app/src/main/java/com/android/streetworkapp/ui/event/AddEvent.kt
Labels: Enhancement :sparkles:

#63 Feat/Fetching function in Park MVVM
  app/src/main/java/com/android/streetworkapp/model/park/ParkRepository.kt
  app/src/main/java/com/android/streetworkapp/model/park/ParkRepositoryFirestore.kt
  app/src/main/java/com/android/streetworkapp/model/park/ParkUtils.kt
  app/src/main/java/com/android/streetworkapp/model/park/ParkViewModel.kt
  app/src/test/java/com/android/streetworkapp/model/park/ParkRepositoryFirestoreTest.kt
  app/src/test/java/com/android/streetworkapp/model/park/ParkUtilsTest.kt
  app/src/test/java/com/android/streetworkapp/model/park/ParkViewModelTest.kt
Labels: Enhancement :sparkles:

#61 Hotfix current user setup
  app/build.gradle.kts
  app/src/androidTest/java/com/android/streetworkapp/ui/profile/AddFriendScreenTest.kt
  app/src/main/java/com/android/streetworkapp/model/user/UserViewModel.kt
  app/src/main/java/com/android/streetworkapp/ui/authentication/SignIn.kt
  app/src/main/java/com/android/streetworkapp/ui/profile/AddFriend.kt
  app/src/test/java/com/android/streetworkapp/model/user/UserViewModelTest.kt
  app/src/test/java/com/android/streetworkapp/ui/authentication/SignInTest.kt
  gradle/libs.versions.toml
Labels: Fixed bug ✅

#79 Hotfix remove the `Livedata`
  app/src/androidTest/java/com/android/streetworkapp/ui/profile/ProfileScreenTest.kt
  app/src/main/java/com/android/streetworkapp/model/user/UserViewModel.kt
  app/src/main/java/com/android/streetworkapp/ui/authentication/SignIn.kt
  app/src/main/java/com/android/streetworkapp/ui/event/AddEvent.kt
  app/src/main/java/com/android/streetworkapp/ui/profile/AddFriend.kt
  app/src/main/java/com/android/streetworkapp/ui/profile/Profile.kt
  app/src/test/java/com/android/streetworkapp/model/user/UserViewModelTest.kt
  app/src/test/java/com/android/streetworkapp/ui/authentication/SignInTest.kt
Labels: Fixed bug ✅

#77 Feat/impove profile screen
  app/src/androidTest/java/com/android/streetworkapp/ui/profile/ProfileComponentsTest.kt
  app/src/androidTest/java/com/android/streetworkapp/ui/profile/ProfileScreenTest.kt
  app/src/main/java/com/android/streetworkapp/ui/profile/Profile.kt
  app/src/main/res/drawable/more_vertical.png
  app/src/main/res/drawable/setting.png
Labels: Enhancement :sparkles:

#80 Feat/basic version of progression mvvm
  app/src/main/java/com/android/streetworkapp/model/progression/Progression.kt
  app/src/main/java/com/android/streetworkapp/model/progression/ProgressionRepository.kt
  app/src/main/java/com/android/streetworkapp/model/progression/ProgressionRepositoryFirestore.kt
  app/src/main/java/com/android/streetworkapp/model/progression/ProgressionViewModel.kt
  app/src/test/java/com/android/streetworkapp/model/progression/ProgressionRepositoryFirestoreTest.kt
  app/src/test/java/com/android/streetworkapp/model/progression/ProgressionViewModelTest.kt
Labels: Enhancement :sparkles:

#81 Feat/implement progress screen UI
  app/src/androidTest/java/com/android/streetworkapp/ui/Progression/ProgressionTest.kt
  app/src/androidTest/java/com/android/streetworkapp/ui/navigation/NavigationActionsTestUi.kt
  app/src/androidTest/java/com/android/streetworkapp/ui/navigation/TopAppBarTest.kt
  app/src/main/java/com/android/streetworkapp/MainActivity.kt
  app/src/main/java/com/android/streetworkapp/ui/navigation/BottomNavigationMenu.kt
  app/src/main/java/com/android/streetworkapp/ui/navigation/NavigationActions.kt
  app/src/main/java/com/android/streetworkapp/ui/navigation/TopAppBar.kt
  app/src/main/java/com/android/streetworkapp/ui/progress/Progression.kt
  app/src/main/java/com/android/streetworkapp/ui/theme/Color.kt
  app/src/main/res/drawable/trophy_24px.xml
  app/src/test/java/com/android/streetworkapp/ui/navigation/NavigationActionsTest.kt
Labels: Enhancement :sparkles:

#83 Hotfix/park mvvm
  app/src/main/java/com/android/streetworkapp/model/park/ParkViewModel.kt
  app/src/test/java/com/android/streetworkapp/model/park/ParkViewModelTest.kt
Labels: Fixed bug ✅

#84 Feat/rating for `Park`
  app/src/main/java/com/android/streetworkapp/model/park/Park.kt
  app/src/main/java/com/android/streetworkapp/model/park/ParkRepository.kt
  app/src/main/java/com/android/streetworkapp/model/park/ParkRepositoryFirestore.kt
  app/src/main/java/com/android/streetworkapp/model/park/ParkViewModel.kt
  app/src/main/java/com/android/streetworkapp/model/parklocation/ParkLocation.kt
  app/src/test/java/com/android/streetworkapp/model/park/ParkRepositoryFirestoreTest.kt
  app/src/test/java/com/android/streetworkapp/model/park/ParkViewModelTest.kt
Labels: Enhancement :sparkles:

#95 Feat/implement park rating
  app/src/androidTest/java/com/android/streetworkapp/ui/parkoverview/ParkRatingTest.kt
  app/src/main/java/com/android/streetworkapp/ui/park/ParkOverview.kt
  app/src/main/res/drawable/add_plus_square.png
Labels: Enhancement :sparkles:

#94 Feat/Fetching user mvvm
  app/src/main/java/com/android/streetworkapp/model/user/UserRepository.kt
  app/src/main/java/com/android/streetworkapp/model/user/UserRepositoryFirestore.kt
  app/src/main/java/com/android/streetworkapp/model/user/UserViewModel.kt
  app/src/test/java/com/android/streetworkapp/model/user/UserRepositoryFirestoreTest.kt
  app/src/test/java/com/android/streetworkapp/model/user/UserViewModelTest.kt
Labels: Enhancement :sparkles:

#91 Feat/Use Nominatim API to display better park names
  app/src/main/java/com/android/streetworkapp/MainActivity.kt
  app/src/main/java/com/android/streetworkapp/model/park/NominatimParkNameRepository.kt
  app/src/main/java/com/android/streetworkapp/model/park/ParkNameRepository.kt
  app/src/main/java/com/android/streetworkapp/model/park/ParkRepository.kt
  app/src/main/java/com/android/streetworkapp/model/park/ParkRepositoryFirestore.kt
  app/src/main/java/com/android/streetworkapp/model/park/ParkViewModel.kt
  app/src/main/java/com/android/streetworkapp/ui/map/MapUi.kt
  app/src/main/java/com/android/streetworkapp/ui/navigation/NavigationActions.kt
  app/src/main/java/com/android/streetworkapp/ui/park/ParkOverview.kt
  app/src/test/java/com/android/streetworkapp/model/park/NominatimParkNameRepositoryTest.kt
  app/src/test/java/com/android/streetworkapp/model/park/ParkViewModelTest.kt
Labels: Enhancement :sparkles:

#102 Hotfix/handle query took too long from Nominatim
  app/src/main/java/com/android/streetworkapp/model/park/NominatimParkNameRepository.kt
  app/src/test/java/com/android/streetworkapp/model/park/NominatimParkNameRepositoryTest.kt
Labels: Fixed bug ✅

#103 Feat bluetooth for friends (backend part)
  app/build.gradle.kts
  app/src/androidTest/java/com/android/streetworkapp/ui/profile/AddFriendScreenTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/android/streetworkapp/MainActivity.kt
  app/src/main/java/com/android/streetworkapp/device/bluetooth/BluetoothClient.kt
  app/src/main/java/com/android/streetworkapp/device/bluetooth/BluetoothConstants.kt
  app/src/main/java/com/android/streetworkapp/device/bluetooth/BluetoothServer.kt
  app/src/main/java/com/android/streetworkapp/model/user/UserViewModel.kt
  app/src/main/java/com/android/streetworkapp/ui/profile/AddFriend.kt
  app/src/main/java/com/android/streetworkapp/ui/profile/BluetoothButton.kt
  app/src/main/java/com/android/streetworkapp/ui/profile/NfcButton.kt
  app/src/test/java/com/android/streetworkapp/device/bluetooth/BluetoothClientTest.kt
  app/src/test/java/com/android/streetworkapp/device/bluetooth/BluetoothServerTest.kt
Labels: Enhancement :sparkles:

#104 Feat/mvvm link to the UI for rating of parks
  app/src/androidTest/java/com/android/streetworkapp/ui/parkoverview/ParkRatingTest.kt
  app/src/main/java/com/android/streetworkapp/MainActivity.kt
  app/src/main/java/com/android/streetworkapp/ui/park/ParkOverview.kt
  app/src/test/java/com/android/streetworkapp/model/park/ParkRatingTest.kt
Labels: Enhancement :sparkles:

#107 Hotfix/Signin fetching user
  app/src/main/java/com/android/streetworkapp/ui/authentication/SignIn.kt
  app/src/test/java/com/android/streetworkapp/ui/authentication/SignInTest.kt
Labels: Fixed bug ✅

#114 Feat bluetooth for friends (frontend part)
  app/src/androidTest/java/com/android/streetworkapp/ui/profile/AddFriendScreenTest.kt
  app/src/androidTest/java/com/android/streetworkapp/ui/profile/BluetoothButtonTest.kt
  app/src/main/java/com/android/streetworkapp/MainActivity.kt
  app/src/main/java/com/android/streetworkapp/ui/profile/AddFriend.kt
  app/src/main/java/com/android/streetworkapp/ui/profile/BluetoothButton.kt
  app/src/main/res/drawable/bluetooth.png
  app/src/main/res/drawable/phone.png
Labels: Enhancement :sparkles:

#105 test/implement end2end for m2
  app/src/androidTest/java/com/android/streetworkapp/end2end/End2EndGeneral.kt
  app/src/androidTest/java/com/android/streetworkapp/end2end/End2EndParks.kt
  app/src/androidTest/java/com/android/streetworkapp/ui/Progression/ProgressionTest.kt
  app/src/androidTest/java/com/android/streetworkapp/ui/navigation/BottomNavigationTest.kt
  app/src/androidTest/java/com/android/streetworkapp/ui/navigation/TopAppBarTest.kt
  app/src/main/java/com/android/streetworkapp/MainActivity.kt
  app/src/main/java/com/android/streetworkapp/model/progression/Progression.kt
  app/src/main/java/com/android/streetworkapp/model/progression/ProgressionRepositoryFirestore.kt
  app/src/main/java/com/android/streetworkapp/model/progression/ProgressionViewModel.kt
  app/src/main/java/com/android/streetworkapp/ui/navigation/BottomNavigationMenu.kt
  app/src/main/java/com/android/streetworkapp/ui/progress/Progression.kt
  app/src/main/res/drawable/trophy_24px.xml
Labels: Enhancement :sparkles:, Fixed bug ✅

#93 Feat/integrate progression backend into UI
  app/src/androidTest/java/com/android/streetworkapp/end2end/End2EndGeneral.kt
  app/src/androidTest/java/com/android/streetworkapp/ui/Progression/ProgressionTest.kt
  app/src/androidTest/java/com/android/streetworkapp/ui/navigation/BottomNavigationTest.kt
  app/src/androidTest/java/com/android/streetworkapp/ui/navigation/TopAppBarTest.kt
  app/src/main/java/com/android/streetworkapp/model/progression/Progression.kt
  app/src/main/java/com/android/streetworkapp/model/progression/ProgressionRepository.kt
  app/src/main/java/com/android/streetworkapp/model/progression/ProgressionRepositoryFirestore.kt
  app/src/main/java/com/android/streetworkapp/model/progression/ProgressionViewModel.kt
  app/src/main/java/com/android/streetworkapp/ui/progress/Progression.kt
  app/src/main/res/drawable/place_holder_achievement_icon.png
  app/src/test/java/com/android/streetworkapp/model/progression/ProgressionViewModelTest.kt
Labels: Enhancement :sparkles:

#110 Feat/display user on the map
  app/build.gradle.kts
  app/src/androidTest/java/com/android/streetworkapp/ui/map/MapTest.kt
  app/src/androidTest/java/com/android/streetworkapp/ui/map/MapUiTest.kt
  app/src/main/java/com/android/streetworkapp/ui/map/Map.kt
  app/src/main/java/com/android/streetworkapp/ui/map/MapUi.kt
  app/src/main/java/com/android/streetworkapp/utils/LocationService.kt
  app/src/main/java/com/android/streetworkapp/utils/PermissionManager.kt
  app/src/test/java/com/android/streetworkapp/ui/map/LocationTest.kt
  gradle/libs.versions.toml
Labels: Help wanted :sos:

#126 Refactor/Update and finish the rework of the progression MVVM
  app/src/main/java/com/android/streetworkapp/model/progression/Progression.kt
  app/src/main/java/com/android/streetworkapp/model/progression/ProgressionRepository.kt
  app/src/main/java/com/android/streetworkapp/model/progression/ProgressionRepositoryFirestore.kt
  app/src/main/java/com/android/streetworkapp/model/progression/ProgressionViewModel.kt
  app/src/main/java/com/android/streetworkapp/ui/event/AddEvent.kt
  app/src/main/java/com/android/streetworkapp/ui/progress/Progression.kt
  app/src/test/java/com/android/streetworkapp/model/progression/ProgressionRepositoryFirestoreTest.kt
  app/src/test/java/com/android/streetworkapp/model/progression/ProgressionViewModelTest.kt
Labels: Refactor 🛠️

#128 Feat/implement text moderation with perspective api
  .github/workflows/ci.yml
  app/build.gradle.kts
  app/src/main/java/com/android/streetworkapp/model/moderation/PerspectiveAPIModels.kt
  app/src/main/java/com/android/streetworkapp/model/moderation/PerspectiveAPIRepository.kt
  app/src/main/java/com/android/streetworkapp/model/moderation/TextModerationRepository.kt
  app/src/main/java/com/android/streetworkapp/model/moderation/TextModerationViewModel.kt
  app/src/test/java/com/android/streetworkapp/model/textmoderation/PerspectiveAPIRepositoryTest.kt
  app/src/test/java/com/android/streetworkapp/model/textmoderation/TextModerationViewModelTest.kt
  gradle/libs.versions.toml
Labels: Enhancement :sparkles:

#136 Feat/training UI
  app/src/androidTest/java/com/android/streetworkapp/end2end/End2EndGeneral.kt
  app/src/androidTest/java/com/android/streetworkapp/ui/Progression/ProgressionTest.kt
  app/src/main/java/com/android/streetworkapp/model/progression/Progression.kt
  app/src/main/java/com/android/streetworkapp/ui/progress/Progression.kt
  app/src/main/res/drawable/front_lever.png
  app/src/main/res/drawable/handstand.png
Labels: Enhancement :sparkles:

#133 Feat/join event
  app/src/androidTest/java/com/android/streetworkapp/event/AddEventTest.kt
  app/src/androidTest/java/com/android/streetworkapp/event/EventOverviewTest.kt
  app/src/main/java/com/android/streetworkapp/MainActivity.kt
  app/src/main/java/com/android/streetworkapp/model/event/EventRepository.kt
  app/src/main/java/com/android/streetworkapp/model/event/EventRepositoryFirestore.kt
  app/src/main/java/com/android/streetworkapp/model/event/EventViewModel.kt
  app/src/main/java/com/android/streetworkapp/ui/event/AddEvent.kt
  app/src/main/java/com/android/streetworkapp/ui/event/EventOverview.kt
  app/src/main/java/com/android/streetworkapp/ui/navigation/BottomNavigationMenu.kt
  app/src/test/java/com/android/streetworkapp/model/event/EventRepositoryFirestoreTest.kt
  app/src/test/java/com/android/streetworkapp/model/event/EventViewModelTest.kt
Labels: Enhancement :sparkles:, Refactor 🛠️

#135 Feat/workout-MVVM
  app/src/main/java/com/android/streetworkapp/model/workout/Exercise.kt
  app/src/main/java/com/android/streetworkapp/model/workout/WorkoutData.kt
  app/src/main/java/com/android/streetworkapp/model/workout/WorkoutRepository.kt
  app/src/main/java/com/android/streetworkapp/model/workout/WorkoutRepositoryFirestore.kt
  app/src/main/java/com/android/streetworkapp/model/workout/WorkoutSession.kt
  app/src/main/java/com/android/streetworkapp/model/workout/WorkoutViewModel.kt
  app/src/test/java/com/android/streetworkapp/model/workout/WorkoutDataTest.kt
  app/src/test/java/com/android/streetworkapp/model/workout/WorkoutRepositoryFirestoreTest.kt
  app/src/test/java/com/android/streetworkapp/model/workout/WorkoutViewModelTest.kt
Labels: Enhancement :sparkles:

#142 Feat/APK custom icon
  app/src/main/AndroidManifest.xml
  app/src/main/ic_launcher_custom-playstore.png
  app/src/main/res/drawable/ic_mono.png
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_custom.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_custom_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher_custom.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_custom_foreground.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_custom_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_custom.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_custom_foreground.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_custom_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_custom.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_custom_foreground.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_custom_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_custom.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_custom_foreground.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_custom_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_custom.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_custom_foreground.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_custom_round.webp
  app/src/main/res/values/ic_launcher_custom_background.xml
Labels: Enhancement :sparkles:

#130 Implement settings for the profile
  app/src/androidTest/java/com/android/streetworkapp/ui/navigation/TopAppBarActionTest.kt
  app/src/androidTest/java/com/android/streetworkapp/ui/parkoverview/ParkRatingTest.kt
  app/src/androidTest/java/com/android/streetworkapp/ui/utils/CustomDialogTest.kt
  app/src/main/java/com/android/streetworkapp/MainActivity.kt
  app/src/main/java/com/android/streetworkapp/ui/navigation/NavigationActions.kt
  app/src/main/java/com/android/streetworkapp/ui/navigation/TopAppBar.kt
  app/src/main/java/com/android/streetworkapp/ui/navigation/TopAppBarManager.kt
  app/src/main/java/com/android/streetworkapp/ui/park/ParkOverview.kt
  app/src/main/java/com/android/streetworkapp/ui/profile/Profile.kt
  app/src/main/java/com/android/streetworkapp/ui/utils/CutsomDialog.kt
  app/src/main/res/drawable/setting.png
  app/src/main/res/drawable/settings.png
Labels: Enhancement :sparkles:

#152 Feat/Update and set gamification in relevant parts of the UI
  app/src/androidTest/java/com/android/streetworkapp/event/EventOverviewTest.kt
  app/src/androidTest/java/com/android/streetworkapp/ui/Progression/GamificationTest.kt
  app/src/main/java/com/android/streetworkapp/MainActivity.kt
  app/src/main/java/com/android/streetworkapp/model/progression/Progression.kt
  app/src/main/java/com/android/streetworkapp/model/user/UserViewModel.kt
  app/src/main/java/com/android/streetworkapp/ui/event/AddEvent.kt
  app/src/main/java/com/android/streetworkapp/ui/event/EventOverview.kt
  app/src/main/java/com/android/streetworkapp/ui/navigation/BottomNavigationMenu.kt
  app/src/main/java/com/android/streetworkapp/ui/profile/AddFriend.kt
  app/src/main/java/com/android/streetworkapp/ui/progress/Gamification.kt
  app/src/main/res/drawable/bronze_achievement_icon.png
  app/src/main/res/drawable/gold_achievement_icon.png
  app/src/main/res/drawable/silver_achievement_icon.png
  app/src/test/java/com/android/streetworkapp/model/progression/ProgressionModelTest.kt
Labels: Enhancement :sparkles:

#149 Feat/integrate text moderation in UI
  app/src/androidTest/java/com/android/streetworkapp/end2end/End2EndCreateEvent.kt
  app/src/androidTest/java/com/android/streetworkapp/end2end/End2EndGeneral.kt
  app/src/androidTest/java/com/android/streetworkapp/end2end/End2EndParks.kt
  app/src/androidTest/java/com/android/streetworkapp/ui/event/AddEventTest.kt
  app/src/androidTest/java/com/android/streetworkapp/ui/event/EventOverviewTest.kt
  app/src/androidTest/java/com/android/streetworkapp/ui/navigation/BottomNavigationTest.kt
  app/src/androidTest/java/com/android/streetworkapp/ui/navigation/TopAppBarTest.kt
  app/src/main/java/com/android/streetworkapp/MainActivity.kt
  app/src/main/java/com/android/streetworkapp/model/event/EventViewModel.kt
  app/src/main/java/com/android/streetworkapp/model/moderation/PerspectiveAPIModels.kt
  app/src/main/java/com/android/streetworkapp/model/moderation/PerspectiveAPIRepository.kt
  app/src/main/java/com/android/streetworkapp/model/moderation/TextModerationRepository.kt
  app/src/main/java/com/android/streetworkapp/model/moderation/TextModerationViewModel.kt
  app/src/main/java/com/android/streetworkapp/ui/event/AddEvent.kt
  app/src/main/java/com/android/streetworkapp/utils/DateUtils.kt
  app/src/test/java/com/android/streetworkapp/model/textmoderation/PerspectiveAPIRepositoryTest.kt
  app/src/test/java/com/android/streetworkapp/model/textmoderation/TextModerationViewModelTest.kt
Labels: Enhancement :sparkles:

#160 Feat/Get and set current user
  app/src/main/java/com/android/streetworkapp/model/user/UserViewModel.kt
  app/src/test/java/com/android/streetworkapp/model/user/UserViewModelTest.kt
Labels: Enhancement :sparkles:

#150 Feat/statistic graph
  app/src/main/java/com/android/streetworkapp/model/workout/WorkoutSession.kt
  app/src/main/java/com/android/streetworkapp/utils/DateUtils.kt
  app/src/main/java/com/android/streetworkapp/utils/GraphData.kt
  app/src/test/java/com/android/streetworkapp/model/workout/WorkoutSessionTest.kt
  app/src/test/java/com/android/streetworkapp/utils/DateUtilsTest.kt
  app/src/test/java/com/android/streetworkapp/utils/GraphDataTest.kt
Labels: Enhancement :sparkles:

#161 hotfix/event overview ui
  app/src/androidTest/java/com/android/streetworkapp/ui/event/EventOverviewTest.kt
  app/src/androidTest/java/com/android/streetworkapp/ui/parkoverview/ParkOverviewTest.kt
  app/src/main/java/com/android/streetworkapp/MainActivity.kt
  app/src/main/java/com/android/streetworkapp/model/park/ParkRepositoryFirestore.kt
  app/src/main/java/com/android/streetworkapp/model/user/UserRepository.kt
  app/src/main/java/com/android/streetworkapp/model/user/UserRepositoryFirestore.kt
  app/src/main/java/com/android/streetworkapp/model/user/UserViewModel.kt
  app/src/main/java/com/android/streetworkapp/ui/event/EventOverview.kt
  app/src/main/java/com/android/streetworkapp/ui/park/ParkOverview.kt
  app/src/main/java/com/android/streetworkapp/utils/DateUtils.kt
  app/src/test/java/com/android/streetworkapp/model/park/ParkRepositoryFirestoreTest.kt
  app/src/test/java/com/android/streetworkapp/model/user/UserRepositoryFirestoreTest.kt
  app/src/test/java/com/android/streetworkapp/model/user/UserViewModelTest.kt
Labels: Enhancement :sparkles:, Fixed bug ✅

#148 Feat/implement helping dialogs in screens
  app/src/androidTest/java/com/android/streetworkapp/ui/navigation/InfoDialogsTest.kt
  app/src/androidTest/java/com/android/streetworkapp/ui/parkoverview/ParkRatingTest.kt
  app/src/androidTest/java/com/android/streetworkapp/ui/utils/CustomDialogTest.kt
  app/src/main/java/com/android/streetworkapp/MainActivity.kt
  app/src/main/java/com/android/streetworkapp/ui/navigation/InfoDialogs.kt
  app/src/main/java/com/android/streetworkapp/ui/navigation/NavigationActions.kt
  app/src/main/java/com/android/streetworkapp/ui/navigation/TopAppBar.kt
  app/src/main/java/com/android/streetworkapp/ui/navigation/TopAppBarManager.kt
  app/src/main/java/com/android/streetworkapp/ui/park/ParkOverview.kt
  app/src/main/java/com/android/streetworkapp/ui/utils/CustomDialog.kt
  app/src/main/java/com/android/streetworkapp/ui/utils/CutsomDialog.kt
  app/src/main/res/drawable/circle_help.png
  app/src/main/res/drawable/octagon_help.png
  app/src/main/res/drawable/square_help.png
  app/src/main/res/drawable/std_help.png
  app/src/main/res/values/strings.xml
Labels: Enhancement :sparkles:

#154 Feat/Creation of the train hub
  app/src/androidTest/java/com/android/streetworkapp/end2end/End2EndCreateEvent.kt
  app/src/androidTest/java/com/android/streetworkapp/end2end/End2EndGeneral.kt
  app/src/androidTest/java/com/android/streetworkapp/end2end/End2EndParks.kt
  app/src/androidTest/java/com/android/streetworkapp/ui/navigation/BottomNavigationTest.kt
  app/src/androidTest/java/com/android/streetworkapp/ui/navigation/TopAppBarTest.kt
  app/src/androidTest/java/com/android/streetworkapp/ui/train/AnimatedCounterTest.kt
  app/src/androidTest/java/com/android/streetworkapp/ui/train/CircularTimerTest.kt
  app/src/androidTest/java/com/android/streetworkapp/ui/train/TrainChallengeScreenTest.kt
  app/src/androidTest/java/com/android/streetworkapp/ui/train/TrainCoachScreenTest.kt
  app/src/androidTest/java/com/android/streetworkapp/ui/train/TrainHubScreenTest.kt
  app/src/androidTest/java/com/android/streetworkapp/ui/train/TrainSoloScreenTest.kt
  app/src/main/java/com/android/streetworkapp/MainActivity.kt
  app/src/main/java/com/android/streetworkapp/ui/navigation/NavigationActions.kt
  app/src/main/java/com/android/streetworkapp/ui/profile/Profile.kt
  app/src/main/java/com/android/streetworkapp/ui/theme/Color.kt
  app/src/main/java/com/android/streetworkapp/ui/train/AnimatedCounter.kt
  app/src/main/java/com/android/streetworkapp/ui/train/CircularTimer.kt
  app/src/main/java/com/android/streetworkapp/ui/train/TrainChallengeScreen.kt
  app/src/main/java/com/android/streetworkapp/ui/train/TrainCoachScreen.kt
  app/src/main/java/com/android/streetworkapp/ui/train/TrainHubScreen.kt
  app/src/main/java/com/android/streetworkapp/ui/train/TrainSoloScreen.kt
  app/src/main/java/com/android/streetworkapp/utils/GraphData.kt
  app/src/main/res/drawable/pushup.png
  app/src/main/res/drawable/training_challenge.png
  app/src/main/res/drawable/training_coach.png
  app/src/main/res/drawable/training_solo.png
Labels: Enhancement :sparkles:

#174 chore: add perspective api key to apk builds
  .github/workflows/apk-builder.yml
Labels: Enhancement :sparkles:
